In [1]:
import tensorflow as tf
tf.random.set_seed(1)

In [7]:
rnn_layer = tf.keras.layers.SimpleRNN(units = 2,
                                     use_bias = True,
                                     return_sequences = True)
# define input shape
# first dimension: batch dimension, use None for variable batch size
# second dimension: sequence dimension, use None for variable sequence length
# last dimension: feature dimension
rnn_layer.build(input_shape = (None, None, 5))

In [8]:
w_xh, w_oo, b_h = rnn_layer.weights

In [9]:
w_xh

<tf.Variable 'simple_rnn_cell_1/kernel:0' shape=(5, 2) dtype=float32, numpy=
array([[ 0.6097033 ,  0.24854195],
       [ 0.0272702 , -0.20167905],
       [ 0.14980292, -0.8360492 ],
       [-0.5969094 ,  0.3790338 ],
       [-0.0149827 , -0.28507388]], dtype=float32)>

In [10]:
w_oo

<tf.Variable 'simple_rnn_cell_1/recurrent_kernel:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.82544434,  0.5644834 ],
       [-0.5644834 ,  0.8254444 ]], dtype=float32)>

In [11]:
b_h

<tf.Variable 'simple_rnn_cell_1/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [12]:
# call forward pass on the rnn_layer
# then manually compute the outputs each step
x_seq = tf.convert_to_tensor([[1.0]*5, [2.0]*5, [3.0]*5],
                            dtype = tf.float32)
x_seq

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.]], dtype=float32)>

In [14]:
# compute output of simpleRNN
output = rnn_layer(tf.reshape(x_seq, shape = (1, 3, 5)))
output

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[ 0.17312294, -0.601329  ],
        [ 0.6816086 , -0.94566447],
        [ 0.92478275, -0.98611367]]], dtype=float32)>

In [16]:
# compute output manually
out_man = []
for t in range(len(x_seq)):
    xt = tf.reshape(x_seq[t], (1, 5))
    print('Time step {} =>'.format(t))
    print('Input :', xt.numpy())
    ht = tf.matmul(xt, w_xh) + b_h
    print('Hidden :', ht.numpy())
    if t>0:
        prev_o = out_man[t-1]
    else:
        prev_o = tf.zeros(shape=(ht.shape))
    ot = ht + tf.matmul(prev_o, w_oo)
    ot = tf.math.tanh(ot)
    out_man.append(ot)
    print('Output (manual): ', ot.numpy())
    print('SimpleRNN output: '.format(t), output[0][t].numpy())
    print()

Time step 0 =>
Input : [[1. 1. 1. 1. 1.]]
Hidden : [[ 0.17488432 -0.6952264 ]]
Output (manual):  [[ 0.17312294 -0.601329  ]]
SimpleRNN output:  [ 0.17312294 -0.601329  ]

Time step 1 =>
Input : [[2. 2. 2. 2. 2.]]
Hidden : [[ 0.34976864 -1.3904527 ]]
Output (manual):  [[ 0.6816086  -0.94566447]]
SimpleRNN output:  [ 0.6816086  -0.94566447]

Time step 2 =>
Input : [[3. 3. 3. 3. 3.]]
Hidden : [[ 0.52465284 -2.085679  ]]
Output (manual):  [[ 0.92478275 -0.98611367]]
SimpleRNN output:  [ 0.92478275 -0.98611367]

