In [1]:
import tensorflow as tf
import numpy as np

In [2]:
np.set_printoptions(precision = 3)

In [3]:
a = np.array([1,2,3], dtype = np.int32)
a

array([1, 2, 3], dtype=int32)

In [4]:
b = [4,5,6]
b

[4, 5, 6]

In [5]:
t_a = tf.convert_to_tensor(a)
t_a

<tf.Tensor: id=0, shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [6]:
print(t_a)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [7]:
t_b = tf.convert_to_tensor(b)
t_b

<tf.Tensor: id=1, shape=(3,), dtype=int32, numpy=array([4, 5, 6], dtype=int32)>

In [8]:
t_ones = tf.ones((2,3))
t_ones.shape

TensorShape([2, 3])

In [9]:
t_ones.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [10]:
t_a.numpy()

array([1, 2, 3], dtype=int32)

In [11]:
const_tensor = tf.constant([1,2,5,np.pi])
print(const_tensor)

tf.Tensor([1.    2.    5.    3.142], shape=(4,), dtype=float32)


In [12]:
const_tensor.numpy()

array([1.   , 2.   , 5.   , 3.142], dtype=float32)

In [13]:
# change data type of a tensor
t_a_new = tf.cast(t_a, tf.int64)
print(t_a_new.dtype)

<dtype: 'int64'>


In [14]:
# transpose a tensor
t = tf.random.uniform(shape = (3,5))
t

<tf.Tensor: id=13, shape=(3, 5), dtype=float32, numpy=
array([[0.464, 0.877, 0.868, 0.306, 0.012],
       [0.802, 0.958, 0.432, 0.397, 0.024],
       [0.574, 0.777, 0.011, 0.515, 0.064]], dtype=float32)>

In [15]:
t_tr = tf.transpose(t)
t_tr

<tf.Tensor: id=15, shape=(5, 3), dtype=float32, numpy=
array([[0.464, 0.802, 0.574],
       [0.877, 0.958, 0.777],
       [0.868, 0.432, 0.011],
       [0.306, 0.397, 0.515],
       [0.012, 0.024, 0.064]], dtype=float32)>

In [16]:
# reshape a tensor
t = tf.zeros((30,))
t

<tf.Tensor: id=18, shape=(30,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [17]:
tf.reshape(t, shape = (5,6))

<tf.Tensor: id=20, shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [18]:
# remove unnecessary dimension
t = tf.zeros((1,2,1,4,1))
t

<tf.Tensor: id=23, shape=(1, 2, 1, 4, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.]]]]], dtype=float32)>

In [19]:
t_sqz = tf.squeeze(t, axis = (2,4))
t_sqz

<tf.Tensor: id=24, shape=(1, 2, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

In [20]:
print(t.shape, ' --> ', t_sqz.shape)

(1, 2, 1, 4, 1)  -->  (1, 2, 4)


In [21]:
tf.random.set_seed(1)

In [23]:
t1 = tf.random.uniform(shape = (5,2), minval = -1.0, maxval=1.0)
t1

<tf.Tensor: id=32, shape=(5, 2), dtype=float32, numpy=
array([[-0.67 ,  0.803],
       [ 0.262, -0.131],
       [-0.416,  0.285],
       [ 0.952, -0.13 ],
       [ 0.32 ,  0.21 ]], dtype=float32)>

In [24]:
t2 = tf.random.normal(shape = (5,2), mean = 0.0, stddev = 1.0)
t2

<tf.Tensor: id=38, shape=(5, 2), dtype=float32, numpy=
array([[ 0.403, -1.088],
       [-0.063,  1.337],
       [ 0.712, -0.489],
       [-0.764, -1.037],
       [-1.252,  0.021]], dtype=float32)>

In [26]:
t3 = tf.multiply(t1, t2).numpy()
t3

array([[-0.27 , -0.874],
       [-0.017, -0.175],
       [-0.296, -0.139],
       [-0.727,  0.135],
       [-0.401,  0.004]], dtype=float32)

In [ ]:
t4 = tf.math.reduce_me