In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.4.1


In [2]:
np.set_printoptions(precision = 3)

### Create tensors

In [5]:
# use numpy array
a = np.array([1,2,3], dtype = np.int32)
t_a = tf.convert_to_tensor(a)
print(t_a)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [7]:
# use list
b = [4,5,6]
t_b = tf.convert_to_tensor(b)
print(t_b)

tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [8]:
t_ones = tf.ones((2,3))
print(t_ones)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [9]:
# access the values
t_ones.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [10]:
# another way to create a tensor
const_tensor = tf.constant([1,2,5,np.pi])
print(const_tensor)

tf.Tensor([1.        2.        5.        3.1415927], shape=(4,), dtype=float32)


### Manipulate data type

In [11]:
# change data type of a tensor
t_a_new = tf.cast(t_a, tf.int64)
print(t_a_new.dtype)

<dtype: 'int64'>


In [12]:
# transpose a tensor
t = tf.random.uniform(shape = (3,5))
t

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0.38080657, 0.8961911 , 0.9217665 , 0.680472  , 0.9554783 ],
       [0.02590024, 0.46309495, 0.49136436, 0.7326813 , 0.03951478],
       [0.21192908, 0.3961258 , 0.9978219 , 0.977653  , 0.43079674]],
      dtype=float32)>

In [13]:
t_tr = tf.transpose(t)
t_tr

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0.38080657, 0.02590024, 0.21192908],
       [0.8961911 , 0.46309495, 0.3961258 ],
       [0.9217665 , 0.49136436, 0.9978219 ],
       [0.680472  , 0.7326813 , 0.977653  ],
       [0.9554783 , 0.03951478, 0.43079674]], dtype=float32)>

In [14]:
# reshape a tensor
t = tf.zeros((30,))
print(t)

tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.], shape=(30,), dtype=float32)


In [15]:
print(tf.reshape(t, shape = (5,6)))

tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(5, 6), dtype=float32)


In [16]:
# remove unnecessary dimension
t = tf.zeros((1,2,1,4,1))
print(t)

tf.Tensor(
[[[[[0.]
    [0.]
    [0.]
    [0.]]]


  [[[0.]
    [0.]
    [0.]
    [0.]]]]], shape=(1, 2, 1, 4, 1), dtype=float32)


In [17]:
t_sqz = tf.squeeze(t, axis = (2,4))
print(t_sqz)

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(1, 2, 4), dtype=float32)


In [18]:
print(t.shape, ' --> ', t_sqz.shape)

(1, 2, 1, 4, 1)  -->  (1, 2, 4)


In [21]:
tf.random.set_seed(1)

In [23]:
t1 = tf.random.uniform(shape = (5,2), minval = -1.0, maxval=1.0)
t1

<tf.Tensor: id=32, shape=(5, 2), dtype=float32, numpy=
array([[-0.67 ,  0.803],
       [ 0.262, -0.131],
       [-0.416,  0.285],
       [ 0.952, -0.13 ],
       [ 0.32 ,  0.21 ]], dtype=float32)>

In [24]:
t2 = tf.random.normal(shape = (5,2), mean = 0.0, stddev = 1.0)
t2

<tf.Tensor: id=38, shape=(5, 2), dtype=float32, numpy=
array([[ 0.403, -1.088],
       [-0.063,  1.337],
       [ 0.712, -0.489],
       [-0.764, -1.037],
       [-1.252,  0.021]], dtype=float32)>

In [26]:
t3 = tf.multiply(t1, t2).numpy()
t3

array([[-0.27 , -0.874],
       [-0.017, -0.175],
       [-0.296, -0.139],
       [-0.727,  0.135],
       [-0.401,  0.004]], dtype=float32)

In [28]:
t4 = tf.math.reduce_mean(t1, axis = 0)
print(t4)

tf.Tensor([0.09  0.207], shape=(2,), dtype=float32)


In [30]:
t5 = tf.linalg.matmul(t1, t2, transpose_b = True)
print(t5.numpy())

[[-1.144  1.115 -0.87  -0.321  0.856]
 [ 0.248 -0.191  0.25  -0.064 -0.331]
 [-0.478  0.407 -0.436  0.022  0.527]
 [ 0.525 -0.234  0.741 -0.593 -1.194]
 [-0.099  0.26   0.125 -0.462 -0.396]]


In [31]:
t6 = tf.linalg.matmul(t1, t2, transpose_a = True)
print(t6.numpy())

[[-1.711  0.302]
 [ 0.371 -1.049]]


In [33]:
# calculate L2 norm of a tensor
norm_t1 = tf.norm(t1, ord = 2, axis = 1).numpy()
print(norm_t1)

[1.046 0.293 0.504 0.96  0.383]


In [38]:
np.sqrt(np.sum(np.square(t1), axis = 1))

array([1.046, 0.293, 0.504, 0.96 , 0.383], dtype=float32)

In [35]:
t1

<tf.Tensor: id=32, shape=(5, 2), dtype=float32, numpy=
array([[-0.67 ,  0.803],
       [ 0.262, -0.131],
       [-0.416,  0.285],
       [ 0.952, -0.13 ],
       [ 0.32 ,  0.21 ]], dtype=float32)>

In [37]:
np.square(t1)

array([[0.449, 0.645],
       [0.069, 0.017],
       [0.173, 0.081],
       [0.905, 0.017],
       [0.103, 0.044]], dtype=float32)

In [39]:
tf.random.set_seed(1)
t = tf.random.uniform((6,))
print(t.numpy())

[0.165 0.901 0.631 0.435 0.292 0.643]


In [40]:
t_splits = tf.split(t, num_or_size_splits=3)
t_splits

[<tf.Tensor: id=66, shape=(2,), dtype=float32, numpy=array([0.165, 0.901], dtype=float32)>,
 <tf.Tensor: id=67, shape=(2,), dtype=float32, numpy=array([0.631, 0.435], dtype=float32)>,
 <tf.Tensor: id=68, shape=(2,), dtype=float32, numpy=array([0.292, 0.643], dtype=float32)>]

In [43]:
tf.random.set_seed(1)
t = tf.random.uniform((5,))
print(t.numpy())

[0.165 0.901 0.631 0.435 0.292]


In [44]:
t_splits = tf.split(t, num_or_size_splits=[3,2])
t_splits

[<tf.Tensor: id=92, shape=(3,), dtype=float32, numpy=array([0.165, 0.901, 0.631], dtype=float32)>,
 <tf.Tensor: id=93, shape=(2,), dtype=float32, numpy=array([0.435, 0.292], dtype=float32)>]

In [45]:
# create a tensorflow dataset from an existing tensor
a = [1.2, 3.4, 7.5, 4.1, 5.0, 1.0]
ds = tf.data.Dataset.from_tensor_slices(a)
print(ds)

<TensorSliceDataset shapes: (), types: tf.float32>


In [47]:
for item in ds:
    print(item)

tf.Tensor(1.2, shape=(), dtype=float32)
tf.Tensor(3.4, shape=(), dtype=float32)
tf.Tensor(7.5, shape=(), dtype=float32)
tf.Tensor(4.1, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


In [48]:
ds_batch = ds.batch(3)
for i,elem in enumerate(ds_batch, 1):
    print(i, elem.numpy())

1 [1.2 3.4 7.5]
2 [4.1 5.  1. ]
